version: '3'

# Define the services/containers to be run
services:
  client:
    build:
      ./angular-src
    image: 
      karimelsayad247/sprints-project-client:latest
    ports:
      - "80:80"
  server:
    build:
        ./
    image:
      karimelsayad247/sprints-project-server:latest
    ports:
      - "8080:8080"